name: Run integration

on: [push]

jobs:
  run-unit-tests:
    name: Run Integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - run: npm run test:integration